export const StorageKeys = Object.freeze({
  DIACRITIZE_PROVIDER: "bm_diacritize_provider",
  DIACRITIZE_MODEL: "bm_diacritize_model",
  LIVE_TRANSCRIPTION: "bm_live_transcription_enabled",
  PROVIDER_MODELS: "bm_provider_models",
  ALERTS_LOG: "bm_alerts_log",
  TEXT_OUTPUT_TARGET: "bm_text_output_target",
  STT_SHORTCUT_BEHAVIOR: "bm_stt_shortcut_behavior",
  TEXT_SHORTCUT_BEHAVIOR: "bm_text_shortcut_behavior",
  SELECTION_MENU_ENABLED: "bm_selection_floating_menu_enabled",
  TARGET_INSERTION_SELECTOR: "bm_target_insertion_selector",
  APPEND_MODE: "bm_append_mode",
  SPEECH_PROVIDER: "bm_speech_provider",
  SPEECH_LANGUAGE: "bm_speech_language",
  SPEECH_MODEL: "bm_speech_model",
  TEXT_MODEL: "bm_text_model",
  SPEECH_API_KEY: "bm_speech_api_key",
  FREE_STT_ENGINE: "bm_free_stt_engine",
  TTS_VOICE_NAME: "bm_tts_voice_name",
  TTS_PROVIDER: "bm_tts_provider",
  TTS_RATE: "bm_tts_rate",
  TTS_PITCH: "bm_tts_pitch",
  TTS_VOLUME: "bm_tts_volume",
  SHORTCUT_DEFAULTS: "bm_shortcut_defaults_v2",
  SHORTCUT_STT: "bm_shortcut_stt",
  SHORTCUT_TEXT: "bm_shortcut_text",
});
